#!/bin/sh

set -e

if ! which curl 2>/dev/null 1>&2; then
    echo "Could not find the curl command"
    echo "Please install the curl package"
    exit 1
fi

if ! which jar 2>/dev/null 1>&2; then
    echo "Could not find the jar command"
    echo "Please install the Sun Java package"
    exit 1
fi

mkdir -p lib

echo "Fetching Clojure..."
curl -O -s http://repo1.maven.org/maven2/org/clojure/clojure/1.3.0-beta1/clojure-1.3.0-beta1.zip
unzip -q clojure-1.3.0-beta1.zip
cp clojure-1.3.0-beta1/clojure-1.3.0-beta1.jar lib/clojure.jar
rm -rf clojure-1.3.0-beta1/
rm clojure-1.3.0-beta1.zip

echo "Fetching Google Closure Library..."
mkdir -p closure/library
cd closure/library
curl -O -s http://closure-library.googlecode.com/files/closure-library-20110323-r790.zip
unzip -q closure-library-20110323-r790.zip
rm closure-library-20110323-r790.zip
cd ..

echo "Fetching Google Closure Compiler..."
mkdir -p compiler
cd compiler
curl -O -s http://closure-compiler.googlecode.com/files/compiler-latest.zip
unzip -q compiler-latest.zip
rm compiler-latest.zip
cd ../..
echo "Building goog.jar..."
jar cf ./lib/goog.jar -C closure/library/closure/ goog

echo "Copying closure/compiler/compiler.jar to lib/..."
cp closure/compiler/compiler.jar lib
