#!/bin/sh
CLASSPATH='lib/*:src/clj:src/cljs'
if [[ `uname` == CYGWIN* ]]; then
  CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
fi

java -server -Xmx2G -Xms2G -Xmn256m -cp $CLASSPATH clojure.main - > core.js <<CLJ
(require :reload '[cljs.compiler :as comp] '[cljs.core])
(binding [comp/*cljs-verbose* true]
  (comp/load-file (comp/repl-env) "cljs/core.cljs"))
CLJ

java -jar closure/compiler/compiler.jar \
  --compilation_level=SIMPLE_OPTIMIZATIONS \
  --warning_level=VERBOSE \
  --formatting=PRETTY_PRINT \
  --jscomp_off=missingProperties \
  --js closure/library/closure/goog/base.js \
  --js closure/library/closure/goog/string/string.js \
  --js closure/library/closure/goog/useragent/jscript.js \
  --js closure/library/closure/goog/string/stringbuffer.js \
  --js closure/library/closure/goog/object/object.js \
  --js closure/library/closure/goog/debug/error.js \
  --js closure/library/closure/goog/asserts/asserts.js \
  --js closure/library/closure/goog/array/array.js \
  --js core.js \
  > coresimple.js

java -jar closure/compiler/compiler.jar \
  --compilation_level=ADVANCED_OPTIMIZATIONS \
  --warning_level=VERBOSE \
  --formatting=PRETTY_PRINT \
  --jscomp_off=missingProperties \
  --js closure/library/closure/goog/base.js \
  --js closure/library/closure/goog/string/string.js \
  --js closure/library/closure/goog/useragent/jscript.js \
  --js closure/library/closure/goog/string/stringbuffer.js \
  --js closure/library/closure/goog/object/object.js \
  --js closure/library/closure/goog/debug/error.js \
  --js closure/library/closure/goog/asserts/asserts.js \
  --js closure/library/closure/goog/array/array.js \
  --js core.js \
  > coreadvanced.js

