#!/bin/sh
if [ "$CLOJURESCRIPT_HOME" = "" ]; then
  CLOJURESCRIPT_HOME="."
fi

CLJSC_CP=''
for next in lib/*: src/clj: src/cljs; do
  CLJSC_CP=$CLJSC_CP$CLOJURESCRIPT_HOME'/'$next
done
java -server -Xmx2G -Xms2G -Xmn256m -cp $CLJSC_CP clojure.main -e \
"(require '[cljs.compiler :as comp])
(def jse (comp/repl-env))
(comp/repl jse)"
