#!/bin/sh
CLASSPATH='lib/*:src/clj:src/cljs'
if [[ `uname` == CYGWIN* ]]; then
  CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
fi

java -server -Xmx2G -Xms2G -Xmn256m -cp $CLASSPATH clojure.main -e \
"(require '[cljs.compiler :as comp])
(def jse (comp/repl-env))
(comp/repl jse)"
