#!/bin/sh

if [ "$CLOJURESCRIPT_HOME" = "" ]; then
  CLOJURESCRIPT_HOME="`dirname $0`/.."
fi

CLJSC_CP=''
for next in classes: lib/*: src/main/clojure: src/main/cljs: test/cljs; do
  CLJSC_CP="${CLJSC_CP}${CLOJURESCRIPT_HOME}/${next}"
done

java -server -cp "$CLJSC_CP" clojure.main -e \
"(require '[cljs.repl :as repl])
(require '[cljs.repl.rhino :as rhino])
(repl/repl (rhino/repl-env) :warn-on-undeclared true)"
