#!/bin/sh

if [ "$CLOJURESCRIPT_HOME" = "" ]; then
  CLOJURESCRIPT_HOME="`dirname $0`/.."
fi

CLJSC_CP=''
for next in classes: lib/*: src/clj: src/cljs: src/aot_cljs: test/cljs; do
  CLJSC_CP="${CLJSC_CP}${CLOJURESCRIPT_HOME}/${next}"
done

java -server -cp "$CLJSC_CP" clojure.main "$@"

