#!/bin/sh

# Compile a single cljs file or a directory of cljs files into a
# single JavaScript file.

if [ "$CLOJURESCRIPT_HOME" = "" ]; then
  CLOJURESCRIPT_HOME="`dirname $0`/.."
fi

CLJTEST_CP=''
for next in lib/*: src/clj: src/cljs: test/cljs: test/clj: lib/clojure.jar; do
  CLJTEST_CP="${CLJTEST_CP}${CLOJURESCRIPT_HOME}/${next}"
done

java -server -cp $CLJTEST_CP clojure.main "$CLOJURESCRIPT_HOME/test/clj/test_runner.clj" "$@"

