#!/bin/sh

rm -rf out
mkdir -p out

echo "Testing exclude all using  string"
bin/cljsc test '{:optimizations :whitespace :exclude "cljs" :output-to "out/exclude-all-with-string.js"}' 
echo "Test exclude all using string done"

echo "Testing exclude all using  vector"
bin/cljsc test '{:optimizations :whitespace :exclude ["cljs"] :output-to "out/exclude-all-with-vector.js"}' 
echo "Test exclude all using  vector done"

