#!/bin/sh

# stop blowing compiled stuff
rm -rf builds/out-self-parity
mkdir -p builds/out-self-parity

# extract needed files from clojure.jar
if [ ! -f lib/clojure.jar ]; then
  echo "Run script/bootstrap first"
  exit 1
fi
jar xvf lib/clojure.jar clojure/template.clj > /dev/null
jar xvf lib/test.check.jar clojure/test/check.cljc clojure/test/check/results.cljc clojure/test/check/clojure_test.cljc clojure/test/check/impl.cljc clojure/test/check/properties.cljc clojure/test/check/generators.cljc clojure/test/check/random.clj clojure/test/check/random/doubles.cljs clojure/test/check/random/longs/bit_count_impl.cljs clojure/test/check/random/longs.cljs clojure/test/check/random.cljs clojure/test/check/rose_tree.cljc > /dev/null
mkdir -p builds/out-self-parity/clojure/test
mv clojure/template.clj builds/out-self-parity/clojure
mv clojure/test builds/out-self-parity/clojure

if ! bin/cljsc src/test/self/self_parity "{:optimizations :none :output-to \"builds/out-self-parity/main.js\" :output-dir \"builds/out-self-parity\" :main self-parity.test :target :nodejs}"; then
  >&2 echo ClojureScript compilation failed
  exit 1
fi;

echo "Testing with Node"
node builds/out-self-parity/main.js
