#!/bin/sh

# stop blowing compiled stuff
rm -rf builds/out-self-parity
mkdir -p builds/out-self-parity

# extract needed files from clojure.jar
if [ ! -f lib/clojure.jar ]; then
  echo "Run script/bootstrap first"
  exit 1
fi
jar xvf lib/clojure.jar clojure/template.clj > /dev/null
jar xvf lib/test.check.jar clojure/test/check/random clojure/test/check/generators.cljc clojure/test/check/rose_tree.cljc > /dev/null
mkdir -p builds/out-self-parity/clojure/test
mv clojure/template.clj builds/out-self-parity/clojure
mv clojure/test/check builds/out-self-parity/clojure/test

bin/cljsc src/test/self/self_parity  "{:optimizations :none :output-to \"builds/out-self-parity/main.js\" :output-dir \"builds/out-self-parity\" :main self-parity.test :target :nodejs}"

echo "Testing with Node"
node builds/out-self-parity/main.js
